### PR TITLE
Option to display 'other' documents (non-acrf and non-supplemental)

### PR DESCRIPTION
**Pull request by tomhub**
Hi Lex,

I added option xsl variable "displayOtherDocuments" to control the display of other documents (not referenced by def:AnnotatedCRF and not referenced by def:DocumentRef).

Also fixed a minor typo in README.md

### CODE REVIEW

**Comment by lexjansen** [comment]
Hi Tomas,

Thanks. I know what you are doing, but I'm not sure that I think it is a good idea.
You may be adding a lot of links to the same document, with just a different title (in 2.0).
If you want to see a document linked from the left bookmark pane you should add it to the def:SupplementalDoc element. That is the semantics of the def:SupplementalDoc element in this stylesheet implementation.
I think it will just add confusion if there are both Supplemental and Other documents.

Also, in your XPath I think you are just looking at def:DocumentRef elements that are grand-children of the MetaDataVersion element. Your not including further descendants. So, for example, you are missing documents referenced from comments or methods (I think).

**Comment by tomhub** [comment]
Hi Lex,

Thanks. I tend to agree that 'Other' type of documents is a bit misconception, and possibly not what user is expecting. However, I think, in such case such 'Other' documents should still be listed, rather than omitted from define.xml display. If user want them in supplemental list, than define.xml should be fixed; if user accidentally left unused leaf, then maybe it would be best to show rather than omit from html display? It is also possible that for some other reasons define.xml references to documents that aren't supplemental or acrf, and user does or doesn't want them listed in the left-pane menu. 

My intention is to show (by default) all $g_MetaDataVersion/def:leaf documents that are not referenced by $g_MetaDataVersion/def:AnnotatedCRF/.. and $g_MetaDataVersion/def:SupplementalDoc/.. Those that are referenced by these elements are already listed in the menu. In case user (probably unexpected define.xml structure) has a leaf not referenced by either, it should still be listed somehow. Ex. ItemDef or Methods references leafs that aren't 'supplemental' and isn't AnnotatedCRF,  then these are listed as 'Other' document. I don't know why someone would want 'Other' documents and not 'Supplemental' documents, but according to define.xml specifications, it seems to me, not all leafs have to be referenced by AnnotatedCRF or SupplementalDoc, thus this option would be able to show (by default) or hide these documents from the menu. Also, @DmitryMK visual defineeditor has option to set document type 'Other' (other types he allowed: "Annotated CRF" and "Supplemental Documents").

MethodDef and CommentDef links to MetaDataVersion/leaf by def:DocumentRef. So both should not have leafs as child elements. ItemGroupDef has def:leaf as child element. It seems to me these leafs should only reference .xpt files, and aren't documents of interest to be listed here.

Let me know what you think.

**Comment by lexjansen** [comment]
Hi Tomas.
Since you specified the type as "Other" in your application (in this case the visual defineeditor) you already specified that you do not want to see those documents displayed in the bookmark pane in the rendered HTML.
The purpose of these documents is that they get listed in their context.
Of course we could still display it as "Other Documents", but that is not the intention of this stylesheet whose main purpose is submission.
I have no intention to mimic applications like visual defineeditor for which Dmitry and Sergei are doing such a great job.
You can review the Other documents in the application.
Also, if you would add this functionality, it should definitely not be the default.

Btw, I will be re-organizing my repo, since I want to keep the PhUSE stylesheet as is.
I started implementing localization in /localization/stylesheets.

Thanks.
Lex

**Comment by tomhub** [comment]
Hi Lex,
Thanks. So it does not make sense to have possibility to list "Other" documents but disabled by default?
p.s. I don't think this stylesheet is mimicking VDE, nor I had such intention.

**Comment by tomhub** [comment]
Closed pull request: upstream stylesheets/define2-0.xsl to be kept as is, and this pull request would modify it.

**Comment by lexjansen** [comment]
Hi Tomas, no problem. I just think some functionalities belong better in an application like VDE.
To give an example. In ARM you may have 25 references to different tables in the CSR. The Other documents list would just list the exact same URL but with 25 different titles. How useful would that be?

**Pull request closed without merging**
